### ISSUE TITLE
How can I run this with the Serverless framework?

### ISSUE THREAD

**Issue by chandima** [BRIKEV/express-jsdoc-swagger#124]
I want to embed this in a Serverless Express lambda running the Serverless framework. Is this possible?

**Comment by kevinccbsg** [comment]
Hi @chandima, I don't have a lot of knowledge of Serverless. However, this library is using the express framework so I think if you can [run an express app using serverless framework](https://www.serverless.com/blog/serverless-express-rest-api) you should be able to access the swagger endpoints.

I'll try to create an example in our Docs when I have more info about it 🤔

**Comment by kevinccbsg** [comment]
Hi @chandima, I was investigating a little bit about this 🤔 and I don't think it is possible and also I don't think it should be configured in this package.

I was testing with a simple file.

```js
// handler.js
const serverless = require("serverless-http");
const express = require("express");
const expressJsdocSwagger = require("express-jsdoc-swagger");

const app = express();

const options = {
  info: {
    version: '1.0.0',
    title: 'Albums store',
    license: {
      name: 'MIT',
    },
  },
  swaggerUIPath: '/api-docs',
  apiDocsPath: '/dev/v3/api-docs',
  filesPattern: ['./handler.js', './*.js'],
  baseDir: __dirname,
};

expressJsdocSwagger(app)(options);

/**
 * GET /
 * @summary This is the summary of the endpoint
 * @return {object} 200 - success response
 */
app.get("/", (req, res, next) => {
  return res.status(200).json({
    message: "Hello from root!",
  });
});

/**
 * GET /hello
 * @summary This is the summary of the endpoint
 * @return {object} 200 - success response
 */
app.get("/hello", (req, res, next) => {
  return res.status(200).json({
    message: "Hello from path!",
  });
});

app.use((req, res, next) => {
  return res.status(404).json({
    error: "Not Found",
  });
});

module.exports.handler = serverless(app);
```
And the serverless.yml file

```yml
org: kevinccbsg
app: my-aws-node-express-api-app
service: my-aws-node-express-api-app

plugins:
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
```

And I could not run it. Apart from that, I read more info about doing this without our package just only using Swagger UI and it requires a lot of configuration ([example 1](https://itnext.io/exploring-an-openapi-swagger-first-approach-to-serverless-development-on-aws-d19f0e9ca257) and [example 2](https://betterdev.blog/serverless-swagger-ui-for-api-gateway/)).

Therefore, Sorry I think we could not provide more support. The only thing I can comment on is that we can edit all the Swagger UI options like in [this example](https://github.com/BRIKEV/express-jsdoc-swagger/blob/master/examples/configuration/swaggerOptions.js#L28) in case this is solved in the future with some Swagger UI config variable.
